### ISSUE TITLE
Does this even work?

### ISSUE THREAD

**Issue by Mo7mud** [geoffreylgv/AdminPanel-MaterializeCSS#2]
It doesn't have any views???
Doesn't have anything at all. Just a blank project.

**Comment by geoffreylgv** [comment]
Hi Dear,

 Of course there is something inside the project. All work perfectly, maybe
when uploading there are some generated files who are not uploaded.
I can zip the folder to send you if you want.

Regards.

**Comment by Mo7mud** [comment]
Yes Please send me the project.
Thank you in advance

**Comment by geoffreylgv** [comment]
Hey @EgyptianM , hope you are doing great.

I have made update, on the repo, even if this took long, sorry for the delay. Really hope it suits something you will like and also why not contribute.

Thanks @EgyptianM
